bugy/script-server

web/js/components/checkbox.js
web/js/components/combobox.js
web/js/components/textfield.js
web/js/index.js

In the previous version the descriptions of parameters specified in the .json-file is unused in the web ui.
This update adds tooltips to the `<input>`s (combobox, checkbox, textfield)

Add tooltips to script parameters

---

launcher.py

Changing the working directory to the app's directory to avoid the "ImportError: No module named 'server'" error be begginner in Python.

Update launcher.py to avoid the No module named 'server' error

---

src/main.py

This allows the currently hardcoded config dir and config files to be set on the command line.
The main driver behind this would be to have separate systemd unit files that refer to different configs.
eg
/lib/systemd/system/script-server@.service
```
[Unit]
Description=Script Server
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
ExecStart=/usr/bin/python3 /opt/script-server/launcher.py --config-file %i.json
[Install]
WantedBy=multi-user.target
```
This allows different configs to be executed (maybe with different auth backends or ports or ssl config etc) as follows:
```
systemctl enable script-server@http
systemctl start script-server@http
systemctl enable script-server@https
systemctl start script-server@https
```
With matching config …

Allow config dir and config file to be specified from command lines

---

src/execution/process_pty.py

os.read spec says that when EOF is reached by the fd, an empty bytes
object is returned.

Fix endless while loop on EOF for pty process

---

src/auth/identification.py
src/model/server_conf.py
src/tests/ip_idenfication_test.py
src/web/server.py

This PR extends the IP based identification to allow the username to be extracted from a specific HTTP request header defined in the server config as follows:
```
{
...
"access": {
"allowed_users": [ ... ],
"admin_users": [ ... ],
"user_header_name": "X-Auth-Name"
}
}
```
This header is only used if the request comes from a trusted IP.
If the configured header does not exist, the identification falls back to the IP based method.
The use case for this, in our case, is an instance of script-server that sits behind a reverse proxy (HAProxy in this case) that does authentication itself, then adds various headers to the request (username, email address, display name etc).

Add option to retrieve username from HTTP header

---

src/execution/logging.py
src/tests/execution_filename_test.py

Hi,
I was playing with script-server for the first time today and noticed you cannot use '/' in the script name as it breaks the logging on the filesystem due to... well, obvious reasons :-)
```
FileNotFoundError: [Errno 2] No such file or directory: 'logs/processes/Group_add/remove_a_member_<host>_200307_134140.log'
```
There might be a better approach to do this as more chars may break this.
For your consideration

Logs - replace forward slash (/) with underscore

---

README.md

Fix link in README, which previously lead to 404 page, instead of actual wiki page with screenshots.
----
Looks like GitHub understands relative links as paths inside the repo, which results in attempt to open `https://github.com/bugy/script-server/blob/master/bugy/script-server/wiki/Admin-interface` and not the actual wiki page with screenshots

chore(docs): Fix admin interface screenshots link

---

src/config/config_service.py

If we will try to create script with path in name, like '/usr/bash' - the script config file will be created by absolute path /usr/bash.json
It's happens because slash wasnt escaped and `path = os.path.join(self._script_configs_folder, _script_name_to_file_name(name))` will not use self._script_configs_folder if second parameter - absolute path

escape path delimiter in script name

---

src/main.py
src/model/server_conf.py

`secret_storage_file` option for move secure cookie key file. Otherwise cookie reseted on docker container recreation.

secret_storage_file config param for store cookie secret

---

src/auth/auth_base.py
src/auth/tornado_auth.py
src/main.py
src/model/server_conf.py

1. --log-folder and --tmp-folder command line arguments to get the files locations more flexible
2. "expiration_days" (non-intеger values are avalible also) in server config file's section "auth" to limit auth cookie life time. The default value is 30 days if the param is underfined.
Changes to be committed:
modified:   src/auth/auth_base.py
modified:   src/auth/tornado_auth.py
modified:   src/main.py
modified:   src/model/server_conf.py

Two issue has been added:

---

src/model/model_helper.py
src/model/parameter_config.py
src/model/script_config.py
src/tests/parameter_config_test.py

This an attempt to support https://github.com/bugy/script-server/issues/217.
I also thought having those variables templated in script's config `description` field aswell.

allow auth.username and auth.audit_name in script values and descriptions

---

src/model/external_model.py
src/model/parameter_config.py
web-src/src/admin/components/scripts-config/ParameterConfigForm.vue
web-src/src/admin/components/scripts-config/parameter-fields.js
web-src/src/common/components/textfield.vue

Adding `max_chars` config parameter to a text field.
I sometime require limit user input to specific number of chars. I've been doing this until now with-in the executed script but I find it much useful this way.

Max chars input validation

---

src/tests/web/server_test.py
src/web/server.py

https://github.com/bugy/script-server/wiki/Reverse-Proxy-setup says to set the `X-Scheme` header but this is not respected because the corresponding flag is not set when instantiating `tornado.httpserver.HTTPServer`. This makes it impossible to terminate TLS on a reverse proxy.

Honor X-headers for reverse proxy support

---

samples/scripts/test.sh
web-src/src/common/components/history/executions-log-table.vue

Sorting history columns introduced in https://github.com/bugy/script-server/pull/430 does not take into account that by default, `sort()` method sorts elements alphabetically. This leads to an unwanted sort result of: `[1, 10, 100, 2, 3]`
This PR enhances sorting to sort numerically, by date property etc.

Correctly sort History columns

---

src/utils/custom_json.py

Fix the following error
```2021-06-25 14:24:14,378 [root.INFO] Starting Script Server (custom version)
2021-06-25 14:24:14,378 [migrations.INFO] Applying migration introduce_access_config
Traceback (most recent call last):
File "launcher.py", line 11, in <module>
main.main()
File "src/main.py", line 79, in main
migrations.migrate.migrate(TEMP_FOLDER, CONFIG_FOLDER, SERVER_CONF_PATH, LOG_FOLDER)
File "src/migrations/migrate.py", line 387, in migrate
migration_descriptor.callable(context)
File "src/migrations/migrate.py", line 211, in __introduce_access_config
json_object = custom_json.loads(content, object_pairs_hook=OrderedDict)
TypeError: loads() got an unexpected keyword argument 'object_pairs_hook'
```

without this migration is broken

---

web-src/src/common/components/history/executions-log-table.vue

A very simple implementation of search functionality in history. Search is implemented client-side. This currently searches only on 'user' and 'script' for the given search text. Suggestions are welcome.
Also fixed vue warning regarding mutating props. See commit - cdf8352891251e448b1858eaab0de8a62d608476
@bugy Need input on where to add this in documentation.
Note: I did not use the current 'SearchPanel' component, since it seemed very specific to the script search.

Feature: history search#572

---

src/migrations/migrate.py

#588 load_runner_files now returns [] in case of non-exisitent runners folder

---

src/communications/destination_email.py

One downstream system we use does not play nice with emails containing attachments. This PR adds the ability to disable attachments when sending email alerts. The default action for users who specify nothing does not change.

Make attachments optional for email alerts

---

src/execution/logging.py
src/migrations/migrate.py

Hi,
Despite https://github.com/bugy/script-server/issues/759 there is still 2 fix missing.
When starting script-server in python:3.13-bookworm docker image:
```
/tmp/script-server/src/migrations/migrate.py:325: SyntaxWarning: invalid escape sequence '\s'
space_matches = re.findall('^\s+', old_content, flags=re.MULTILINE)
/tmp/script-server/src/execution/logging.py:292: SyntaxWarning: invalid escape sequence '\w'
match = re.fullmatch('([\w_]+):(.*\r?\n)', line)
2025-01-13 15:25:37,634 [root.INFO] Starting Script Server (custom version)
2025-01-13 15:25:37,636 [asyncio.DEBUG] Using selector: EpollSelector
Server is running on: http://0.0.0.0:5000
```
This PR fix these 2 files

fix: SyntaxWarning: invalid escape sequence

---

src/execution/logging.py
src/model/server_conf.py

#788: added possibilit to disable logging per script

#788: added possibilit to disable logging per script

---

src/tests/execution_logging_test.py
src/tests/model_helper_test.py
src/tests/server_conf_test.py
src/tests/web/server_test.py

This PR migrates from `unittest.assertEquals` to `unittest.assertEqual` which is deprecated from Python2.7 and considered bad practice to use:
```python
DeprecationWarning: Please use assertEqual instead.
```

migrate to `unittest.assertEqual`
